package com.cyfres.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Season generated by hbm2java
 */
@Entity
@Table(name = "season", catalog = "cyfres")
public class Season implements java.io.Serializable {

	private Integer id;
	private String number;
	private int series;

	public Season() {
	}

	public Season(int series) {
		this.series = series;
	}

	public Season(String number, int series) {
		this.number = number;
		this.series = series;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "number", length = 64)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "series", nullable = false)
	public int getSeries() {
		return this.series;
	}

	public void setSeries(int series) {
		this.series = series;
	}

}
