package com.cyfres.model;


import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.cyfres.model.*;



/**
 * Series generated by hbm2java
 */
@Entity
@Table(name = "series", catalog = "cyfres")
public class Series implements java.io.Serializable {

	private Integer id;
	private String name;
	private String rating;
	private String ratingCount;
	private String image;
	private String critic;
	private String review;
	private String lastUpdate;
	private String lastEpisode;
	private String latestEpisode;
	private String url;
	private Set<Genre> genre;
	private Set<Cast> cast;
	public Series() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	
	@OneToMany(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
	@JoinTable(name="series_casts",
	joinColumns={@JoinColumn(name="series_id", referencedColumnName="id")},
	inverseJoinColumns={@JoinColumn(name="casts_id", referencedColumnName="id")})
	public Set<Cast> getCast() {
		return cast;
	}


	public void setCast(Set<Cast> cast) {
		this.cast = cast;
	}


	@OneToMany(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
	@JoinTable(name="series_genres",
	joinColumns={@JoinColumn(name="series_id", referencedColumnName="id")},
	inverseJoinColumns={@JoinColumn(name="genres_id", referencedColumnName="id")})
	public Set<Genre> getGenre() {
		return genre;
	}


	public void setGenre(Set<Genre> genre) {
		this.genre = genre;
	}


	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "rating", length = 64)
	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	@Column(name = "ratingCount", length = 64)
	public String getRatingCount() {
		return this.ratingCount;
	}

	public void setRatingCount(String ratingCount) {
		this.ratingCount = ratingCount;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "critic")
	public String getCritic() {
		return this.critic;
	}

	public void setCritic(String critic) {
		this.critic = critic;
	}

	@Column(name = "review")
	public String getReview() {
		return this.review;
	}

	public void setReview(String review) {
		this.review = review;
	}

	@Column(name = "lastUpdate")
	public String getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(String lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "lastEpisode")
	public String getLastEpisode() {
		return this.lastEpisode;
	}

	public void setLastEpisode(String lastEpisode) {
		this.lastEpisode = lastEpisode;
	}

	@Column(name = "latestEpisode")
	public String getLatestEpisode() {
		return this.latestEpisode;
	}

	public void setLatestEpisode(String latestEpisode) {
		this.latestEpisode = latestEpisode;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	

}
